# Generated by Django 6.1.1 on 2026-09-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название аромата')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс')], max_length=1, verbose_name='Пол')),
                ('volume_ml', models.IntegerField(default=50, verbose_name='Объем (мл)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)')),
                ('notes', models.CharField(max_length=255, verbose_name='Ноты аромата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
        ),
    ]
