# Generated by Django 6.1.1 on 2026-09-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='Изображение'),
        ),
    ]
