# Generated by Django 6.1.1 on 2026-09-29 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_perfume_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='volume_ml',
        ),
        migrations.AddField(
            model_name='perfume',
            name='in_stock_almaty',
            field=models.BooleanField(default=True, verbose_name='В наличии: Алматы (Dostyk Plaza)'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='in_stock_bishkek_asia',
            field=models.BooleanField(default=True, verbose_name='В наличии: Бишкек (Азия Молл)'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='in_stock_bishkek_center',
            field=models.BooleanField(default=True, verbose_name='В наличии: Бишкек (ЦУМ / Центр)'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Участвует в акции'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (для акции)'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='promo_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст акции (напр. Скидка -20%)'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.TextField(verbose_name='Ноты аромата'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
