# Generated by Django 6.1.1 on 2026-09-30 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_remove_perfume_description_remove_perfume_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='perfume',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='in_stock_almaty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='in_stock_bishkek_asia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='in_stock_bishkek_center',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='promo_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
    ]
